/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ISystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FUNGIBLE_MODULE_ADDRESS"
      | "gasCoinMRC20ByChainId"
      | "gasMusePoolByChainId"
      | "gasPriceByChainId"
      | "uniswapv2FactoryAddress"
      | "wMuseContractAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FUNGIBLE_MODULE_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasCoinMRC20ByChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gasMusePoolByChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gasPriceByChainId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapv2FactoryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wMuseContractAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FUNGIBLE_MODULE_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasCoinMRC20ByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasMusePoolByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasPriceByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapv2FactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wMuseContractAddress",
    data: BytesLike
  ): Result;
}

export interface ISystem extends BaseContract {
  connect(runner?: ContractRunner | null): ISystem;
  waitForDeployment(): Promise<this>;

  interface: ISystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FUNGIBLE_MODULE_ADDRESS: TypedContractMethod<[], [string], "view">;

  gasCoinMRC20ByChainId: TypedContractMethod<
    [chainID: BigNumberish],
    [string],
    "view"
  >;

  gasMusePoolByChainId: TypedContractMethod<
    [chainID: BigNumberish],
    [string],
    "view"
  >;

  gasPriceByChainId: TypedContractMethod<
    [chainID: BigNumberish],
    [bigint],
    "view"
  >;

  uniswapv2FactoryAddress: TypedContractMethod<[], [string], "view">;

  wMuseContractAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FUNGIBLE_MODULE_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gasCoinMRC20ByChainId"
  ): TypedContractMethod<[chainID: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "gasMusePoolByChainId"
  ): TypedContractMethod<[chainID: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "gasPriceByChainId"
  ): TypedContractMethod<[chainID: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "uniswapv2FactoryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wMuseContractAddress"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
