/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MuseReceiver,
  MuseReceiverInterface,
} from "../../MuseInterfaces.sol/MuseReceiver";

const _abi = [
  {
    type: "function",
    name: "onMuseMessage",
    inputs: [
      {
        name: "museMessage",
        type: "tuple",
        internalType: "struct MuseInterfaces.MuseMessage",
        components: [
          {
            name: "museTxSenderAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "sourceChainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "destinationAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "museValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "message",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onMuseRevert",
    inputs: [
      {
        name: "museRevert",
        type: "tuple",
        internalType: "struct MuseInterfaces.MuseRevert",
        components: [
          {
            name: "museTxSenderAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "sourceChainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "destinationAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "destinationChainId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "remainingMuseValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "message",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class MuseReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): MuseReceiverInterface {
    return new Interface(_abi) as MuseReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MuseReceiver {
    return new Contract(address, _abi, runner) as unknown as MuseReceiver;
  }
}
