/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MRC20__factory } from "./MRC20__factory";
export { MRC20Errors__factory } from "./MRC20Errors__factory";
