/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMRC20__factory } from "./IMRC20__factory";
export { IMRC20Metadata__factory } from "./IMRC20Metadata__factory";
export { MRC20Events__factory } from "./MRC20Events__factory";
